name: country_list_pick
description: Flutter plugin project to pick country code, will show code country, dial code, flag country, and name country.
version: 1.0.1+5
homepage: https://github.com/hifiaz/country-list-pick

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^2.0.0
  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - flags/
